# cloudbuild.yaml
steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/my-app:${SHORT_SHA}',  # Tag the image with commit SHA
      '.'  # Build context (root of your repo)
    ]

  # Step 2 (Optional): Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'gcr.io/$PROJECT_ID/my-app:${SHORT_SHA}'
    ]

# Optional: Set images to make them appear in Google Cloud Build UI
images:
  - 'gcr.io/$PROJECT_ID/my-app:${SHORT_SHA}'

# Optional substitutions
substitutions:
  _TAG: 'latest'  # You can override this when triggering builds


options:
  logging: CLOUD_LOGGING_ONLY