# cloudbuild.yaml
substitutions:
  _REGION: "europe-west1"  # Artifact Registry & Cloud Run region
  _REPOSITORY: "wolfgangB33r/dt-settings-cleanup-job"  # Artifact Registry repository name
  _JOB: "dt-settings-cleanup-job"          # Cloud Run Job name

steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_JOB}:${SHORT_SHA}',
        '.'
      ]

  # Step 2: Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_JOB}:${SHORT_SHA}'
      ]

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_JOB}:${SHORT_SHA}'

# Cloud logs settings
options:
  logging: CLOUD_LOGGING_ONLY