steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/hello-job', '.']

  # Push it to Container Registry / Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/hello-job']

  # Deploy it as a Cloud Run Job
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'jobs'
      - 'create'
      - 'hello-job'
      - '--image'
      - 'gcr.io/$PROJECT_ID/hello-job'
      - '--region'
      - 'us-central1'
      - '--no-traffic'

options:
  logging: CLOUD_LOGGING_ONLY
